---
name: xgboost_
make_window_datasets:
  step_id: "normal=0.1_w=1"
  window_manager:
    window_size: 1
    window_step: 1
    n_periods: -1
    normal_data_prop:
      value: 0.1
      lt__1.0:
        normal_sampling_seed: 0
    window_min_ano_coverage: 0.2
    window_weak_ano_policy: drop
    class_balancing:
      value: none  # *choice* "naive_ano" only if multiple ano classes
      ne__none:
        class_balancing_seed: 0
    dropped_anomaly_types: "7"
    anomaly_augmentation:
      value: none  # "none", "smote", "borderline_smote", "svm_smote" or "adasyn"
      ne__none:
        ano_augment_n_per_normal: 500
        ano_augment_seed: 0

train_window_scorer:
  step_id: xgb
  binary_mode: True
  imbalance_handling: "none"
  n_estimators: 100
  max_depth: 6
  min_child_weight: 1
  subsample: 1.0
  learning_rate: 0.3
  gamma: 0.0
  max_delta_step: 0
  random_state: 0
...